# Generated by Django 5.2.1 on 2025-05-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_amenity_service_tag_roomcategory_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
