# Generated by Django 5.2.1 on 2025-05-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_client_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='charts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
