# Generated by Django 5.2.1 on 2025-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_chartimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='Staying with children'),
        ),
    ]
