# Generated by Django 5.2.1 on 2025-09-17 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_banner_partner_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificates',
            field=models.TextField(blank=True, help_text='Text description of company certificates', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to company video (e.g., YouTube embed link)', null=True),
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('event', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='hotel.companyinfo')),
            ],
            options={
                'verbose_name_plural': 'Company History Entries',
                'ordering': ['year'],
            },
        ),
    ]
