# Generated by Django 5.2.1 on 2025-09-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_companyinfo_certificates_companyinfo_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (e.g., MP4, WebM)', null=True, upload_to='company/videos/'),
        ),
    ]
